# Generated by Django 5.2.17 on 2026-09-02 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('counselor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_notes', to='patients.patient')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientDailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='Daily Round', help_text='e.g. Morning Round, Evening Round', max_length=50)),
                ('mental_condition', models.CharField(blank=True, max_length=255)),
                ('physical_condition', models.CharField(blank=True, max_length=255)),
                ('mood', models.CharField(blank=True, max_length=100)),
                ('withdrawal_symptoms', models.TextField(blank=True)),
                ('sleep_quality', models.CharField(blank=True, max_length=100)),
                ('appetite', models.CharField(blank=True, max_length=100)),
                ('medicines_given', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(help_text='e.g. 50mg, 1 tablet', max_length=100)),
                ('frequency', models.CharField(help_text='e.g. Twice daily (BD), TDS, SOS', max_length=100)),
                ('duration', models.CharField(help_text='e.g. 7 days, 1 month', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_stopped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineAdministrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_logs', to='clinical.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='StatutoryFormRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('formC', 'Form C - Independent Admission [Sec 86]'), ('formD', 'Form D - Minor Admission [Sec 87]'), ('formE', 'Form E - High Support Admission [Sec 89]'), ('form4', 'Form 4 - Restraint & Seclusion Log'), ('form5', 'Form 5 - Suicide Risk Management'), ('dama', 'DAMA - Discharge Against Medical Advice'), ('formI', 'Form I - Leave of Absence [Sec 91]'), ('formJ', 'Form J - Police Intimation (Absconding) [Sec 103]')], max_length=20)),
                ('form_data', models.JSONField(blank=True, default=dict, help_text='Stored dynamic JSON key-values of the form')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_forms', to='patients.patient')),
            ],
        ),
    ]
