# Generated by Django 5.2.17 on 2026-09-02 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20, verbose_name='Govt ID / Aadhaar')),
                ('address', models.TextField(blank=True)),
                ('admission_type', models.CharField(choices=[('independent', 'Independent Admission (Sec 86)'), ('involuntary', 'Involuntary / High Support (Sec 89)'), ('minor', 'Minor Admission (Sec 87)')], default='independent', max_length=20)),
                ('admission_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Currently Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('dama', 'Discharged Against Medical Advice (DAMA)')], default='active', max_length=20)),
                ('addiction_type', models.CharField(help_text='e.g. Alcohol, Opioids, Polysubstance, Gambling', max_length=100)),
                ('medical_history', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(max_length=150)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_relation', models.CharField(blank=True, max_length=50)),
                ('school_name', models.CharField(blank=True, help_text='For minors', max_length=150)),
                ('grade', models.CharField(blank=True, help_text='For minors', max_length=50)),
                ('legal_reason', models.TextField(blank=True)),
                ('legal_remarks', models.TextField(blank=True)),
                ('self_consent', models.BooleanField(default=False)),
                ('digital_signature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.institution')),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_visible_to_family', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
